<a href="https://colab.research.google.com/github/Slrosales/Altera-VGA-Audio-Solution/blob/main/VGA%20Solution/Componentes_RGB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Librerias

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import os
import numpy as np
import imageio
import matplotlib.pyplot as plt
from PIL import Image

# Preparación de la imagen

In [ ]:
dirpath = os.getcwd()
print("current directory is : " + dirpath)

foldername = os.path.basename(dirpath)
print("Directory name is : " + foldername)
os.chdir("/content/drive/MyDrive/Estructura_del_Computador/Python")

dirpath = os.getcwd()
print("current directory is : " + dirpath)

foldername = os.path.basename(dirpath)
print("Directory name is : " + foldername)

current directory is : /content
Directory name is : content
current directory is : /content/drive/MyDrive/Estructura_del_Computador/Python
Directory name is : Python


In [ ]:
imagen = imageio.imread(os.path.join(dirpath,'Eduardo_Zurek_ejemplo.jpg'))

im0 = Image.fromarray(imagen)
im0 = im0.resize((128,128), Image.ANTIALIAS)
imagen = np.asarray(im0,'uint8')
im1 = Image.fromarray(imagen)
im1 = im1.save("EZ_128.bmp")

In [ ]:
print(imagen.shape)

red = imagen[:,:,0].flatten()
print(red.shape)

green = imagen[:,:,1].flatten()
print(green.shape)

blue = imagen[:,:,2].flatten()
print(blue.shape)

(128, 128, 3)
(16384,)
(16384,)
(16384,)


In [ ]:
print(red[1:10])
print(green[1:10])
print(blue[1:10])

[ 94  98 100 102  95  98  92  54  58]
[142 139 143 148 143 142 142 132 143]
[ 9  1  2  6  3  3 12 34 44]


In [ ]:
azul = np.uint8(blue)
verde = np.uint8(green)
rojo = np.uint8(red)
representacion = np.uint16(rojo+verde+azul)

In [ ]:
print(bin(azul[0]))
print(len(azul))
for i in range(20):
  print([hex(rojo[i]),bin(rojo[i]),hex(verde[i]),bin(verde[i]),hex(azul[i]),bin(azul[i])])

0b1100
16384
['0x66', '0b1100110', '0x91', '0b10010001', '0xc', '0b1100']
['0x5e', '0b1011110', '0x8e', '0b10001110', '0x9', '0b1001']
['0x62', '0b1100010', '0x8b', '0b10001011', '0x1', '0b1']
['0x64', '0b1100100', '0x8f', '0b10001111', '0x2', '0b10']
['0x66', '0b1100110', '0x94', '0b10010100', '0x6', '0b110']
['0x5f', '0b1011111', '0x8f', '0b10001111', '0x3', '0b11']
['0x62', '0b1100010', '0x8e', '0b10001110', '0x3', '0b11']
['0x5c', '0b1011100', '0x8e', '0b10001110', '0xc', '0b1100']
['0x36', '0b110110', '0x84', '0b10000100', '0x22', '0b100010']
['0x3a', '0b111010', '0x8f', '0b10001111', '0x2c', '0b101100']
['0x4f', '0b1001111', '0x91', '0b10010001', '0x1c', '0b11100']
['0x58', '0b1011000', '0x86', '0b10000110', '0x1f', '0b11111']
['0xcc', '0b11001100', '0xad', '0b10101101', '0x3a', '0b111010']
['0x6e', '0b1101110', '0x95', '0b10010101', '0x33', '0b110011']
['0x28', '0b101000', '0x89', '0b10001001', '0x20', '0b100000']
['0x31', '0b110001', '0x75', '0b1110101', '0x20', '0b100000']
['0

# Salida

In [ ]:
f = open("salida_rojo.txt","w")
c = 0
for i in rojo:
  if c % 16 == 0:
    f.write("\n")
  t = bin(i)
  f.write('"'+t[2:].rjust(8,'0')+'",')
  c=c+1
f.close()

In [ ]:
f = open("salida_azul.txt","w")
c = 0
for i in azul:
  if c % 16 == 0:
    f.write("\n")
  t = bin(i)
  f.write('"'+t[2:].rjust(8,'0')+'",')
  c=c+1
f.close()

In [ ]:
f = open("salida_verde.txt","w")
c = 0
for i in verde:
  if c % 16 == 0:
    f.write("\n")
  t = bin(i)
  f.write('"'+t[2:].rjust(8,'0')+'",')
  c=c+1
f.close()